version: "3.9"
services:
  worker1:
    build: .
    network_mode: "host"
  worker2:
    build: .
    network_mode: "host"
  worker3:
    build: .
    network_mode: "host"
  worker4:
    build: .
    network_mode: "host"
  worker5:
    build: .
    network_mode: "host"
  worker6:
    build: .
    network_mode: "host"
  worker7:
    build: .
    network_mode: "host"
  worker8:
    build: .
    network_mode: "host"